### ISSUE TITLE
Quick reply duplication

### ISSUE THREAD

**Issue by exomarty** [pichalite/nodebb-theme-slick#2]
on nodebb version 1.4.1 using quickreply duplicates the post

thnak you and great theme

**Comment by pichalite** [comment]
@exomarty I am not able to reproduce. Probably some issue with your setup.

**Comment by exomarty** [comment]
thats strange, i think it can be realated with a node bug, opened another issue
https://github.com/NodeBB/NodeBB/issues/5297

i have tested on my production and on local dev with same results and no other relevant plugins

**Comment by exomarty** [comment]
solved with ./nodebb build
