### ISSUE TITLE
stylesheets break going from account->settings to any other page

### ISSUE THREAD

**Issue by freakbyte** [pichalite/nodebb-theme-slick#20]
using nodebb 1.7.3, slick 1.1.4 & dark skin
when i go from the account->settings page to any other page body loses skin-dark class and gains skin-yeti

can you reproduce this or is it on my end?
thanks

**Comment by RandomAnimeGamer** [comment]
I know it's been a few years, but this is a regression. I just installed nodeBB fresh yesterday, and I get this same error.
