### ISSUE TITLE
Add margin to tags block in topic

### ISSUE THREAD

**Issue by rez0n** [pichalite/nodebb-theme-slick#4]
Hello! Need to add margin-bottom: 10px; to .pull-left
![add-margin-10px](https://cloud.githubusercontent.com/assets/725860/23529044/b53402fa-ffa4-11e6-9e7b-0cdf052e2980.png)

**Comment by pichalite** [comment]
Fixed in https://github.com/pichalite/nodebb-theme-slick/commit/157422548232582f7a4fbdc00ea563934ebacb71
