### ISSUE TITLE
Profile Changes Not Saving

### ISSUE THREAD

**Issue by skeddles** [pichalite/nodebb-theme-slick#53]
When I go to edit profile, and change my full name, about me, signature, etc, then click save, I get the [success popup](![image](https://user-images.githubusercontent.com/2721332/118370459-cbcddf00-b575-11eb-8fec-7d8cd4b8f376.png)).

But then when I hard refresh the page, or go to my profile page, you can see that the fields have not changed.

I've tried it many times, and it never seems to save.

If I switch to the persona theme and edit my profile, I get the same popup, but the changes **DO** save. 

I've reinstalled the theme, made sure it's the latest version (1.4.6), and switched back between persona and slick multiple times, and persona always works and slick always doesn't.

**Comment by skeddles** [comment]
I looked at the requests the theme made:

this is the request made when saving the profile from slick
![firefox_2021-05-15_13-10-29](https://user-images.githubusercontent.com/2721332/118372304-fcfedd00-b57e-11eb-8344-8293593a265d.png)

this is the request made when saving the profile with persona
![firefox_2021-05-15_13-10-38](https://user-images.githubusercontent.com/2721332/118372316-0be58f80-b57f-11eb-9ce9-2d8c0c55099a.png)


I think it's because the `<input>`s are missing names, and the form is missing `component="profile/edit/form"`

**Comment by skeddles** [comment]
opened a pull request

**Comment by barisusakli** [comment]
https://github.com/pichalite/nodebb-theme-slick/pull/54
