### ISSUE TITLE
Count of views in topic list

### ISSUE THREAD

**Issue by rez0n** [pichalite/nodebb-theme-slick#6]
In topic list, count of views not in 'human readable number'. 
![topic-view-count](https://cloud.githubusercontent.com/assets/725860/23530489/8ef7d390-ffaa-11e6-8d38-0e2b546d39e9.png)

But on bottom of post is good.
![topic-view-count-normal](https://cloud.githubusercontent.com/assets/725860/23530501/9cd094de-ffaa-11e6-9156-f0fdc706c1f4.png)

**Comment by pichalite** [comment]
Fixed in https://github.com/pichalite/nodebb-theme-slick/commit/157422548232582f7a4fbdc00ea563934ebacb71
