### ISSUE TITLE
Long URLs are getting cut off

### ISSUE THREAD

**Issue by ReyKoxha** [pichalite/nodebb-theme-slick#7]
As the title says long URLs like:
http://thisisalongdomain.tld/longrandomaiojdaijdajdoaspidjaso

Are getting cut to:
http://thisisalongdomain.tld/longr...

A little suggestion:
How about making this optional (if possible)?

**Comment by pichalite** [comment]
I can't reproduce it. See here

http://slick.pichalite.com/topic/3/hey/10

**Comment by pichalite** [comment]
@ReyKoxha Need more info. What route is it happening. Do you have a link where I can see it happening?

**Comment by ReyKoxha** [comment]
An example (no matter if sidebar is there or not):
https://forum.meizufans.eu/topic/7590/meizufans-2017-whats-ahead-of-us/10

**Comment by pichalite** [comment]
@ReyKoxha I have checked you site. It's not the theme that's doing it. It's the composer (redactor) doing that.
